import type { Metadata } from "next";

import "./globals.css";
import SideBar from "@/components/SideBar";
import SessionProvider from "@/components/SessionProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import Login from "@/components/Login";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  
  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          {
            session ? (
              <div className="flex">
                <div className="bg-[#202123] max-w-xs h-screen overflow-y-auto md:min-w-[20rem]">
                  <SideBar />
                </div>
                {/* Client Provider */}
                <div className="flex-1 bg-[#343541]">
                  {children}
                </div>
              </div>
            ) : (
              <Login />
            )
          }
        </SessionProvider>
      </body>
    </html>
  );
}
